# Funding
# For correspondence, please send an email to:
# Farhan Kurnia Pratama <farhnkrnapratma@gmail.com> <farhnkrnapratma@protonmail.com>

github: farhnkrnapratma
open_collective: farhnkrnapratma
ko_fi: farhnkrnapratma
buy_me_a_coffee: farhnkrnapratma
